import LoaderOverlayGeneral from '../components/share/LoaderOverlayGeneral'
import { FooterComponent } from '../components/share/footer/FooterComponent'
import HeaderComponent from '../components/share/header/HeaderComponent'
import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='es'>
      <body className='flex flex-col' suppressHydrationWarning={true}>
        <LoaderOverlayGeneral />
        <HeaderComponent />
        <main>
          {children}
        </main>
        <FooterComponent />
        </body>
    </html>
  )
}
